name: Publish
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish to FlakeHub"
        type: "string"
        required: true
jobs:
  flakehub:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write # Necessary for authenticating against FlakeHub
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Push to flakehub
        uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          tag: "${{ inputs.tag }}"

